### PR TITLE
Added some extra folders for MacOS PATH variable

### PR DESCRIPTION
**Pull request by atnartur**

### CODE REVIEW

**Comment by chrokh** [comment]
Cool. Thanks! Could you please just shortly explain why this is needed?

**Comment by atnartur** [comment]
I added Mono Framework installation dir to PATH for using mono compiler in plugin. In my case there is not mcs binary in /usr/local/bin. And sublime plugin cannot to see normal value of PATH. It see only following: 
```
[path: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin]
```

But in console PATH variable contains following:
```
/Users/atnartur/.dnx/bin:/usr/local/sbin:/usr/local/opt/php55/bin:/Users/atnartur/bin:/Users/atnartur/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands
``` 

So I added `/Library/Frameworks/Mono.framework/Versions/Current/Commands` path to PATH for working with mono compiler.

**Comment by chrokh** [comment]
Many thanks for bringing this to my attention, and thanks for the pull request. It seems it may have come as an effect of a Mac OS update that changes [the way GUI applications access PATH](https://forum.sublimetext.com/t/how-to-set-path-on-os-x-so-sublime-can-see-it/11842).

I added [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) as a dependency of this package. It's installable via Package Control. Please install `SublimeFixMacPath` and then reinstall `csharp-build-singlefile-sublime-text-2`.

7bcebda6ded07308547b0e13aab3936fe0c39dfa removes the hard-coded PATH and adds the new dependency in the [README](https://github.com/chrokh/csharp-build-singlefile-sublime-text-2/blob/master/README.md).

Does this fix your issue?

**Comment by chrokh** [comment]
This means that your PATH variable should be loaded correctly and there is no need for additional paths to be manually added to this package. I'm assuming this works, and thus close the PR. Please say so if it doesn't :)

**Comment by atnartur** [comment]
Thanks! Everything is OK!

**Pull request closed without merging**
